default:
  image: php:8
  before_script:
    # install dependencies
    - apt-get -yqq update
    - apt-get -yqq install git zip unzip subversion default-mysql-client default-libmysqlclient-dev gettext --fix-missing
    - bin/ci/install_composer.sh
    - composer install

stages:
  - test
  - release

lint:
  stage: test
  script:
    # run lint
    - make lint
    # try to pack it
    - make pack

release:
  stage: release
  only:
    - tags
  script:
    - make pack
  artifacts:
    untracked: false
    when: on_success
    paths:
      - "miguel-*.zip"
