default:
  image:
    name: php:8
    entrypoint: ["/bin/bash", "-c"]

stages:
  - test
  - release

lint:
  stage: test
  script:
    # install dependencies
    - apt-get -yqq update
    - apt-get -yqq install git zip unzip subversion default-mysql-client default-libmysqlclient-dev --fix-missing
    - bin/ci/install_composer.sh
    - composer install
    # run lint
    - make lint

release:
  stage: release
  only:
    - tags
  script:
    - apt-get update
    - apt-get install zip gettext -y
    - make pack
  artifacts:
    untracked: false
    when: on_success
    paths:
      - "miguel-*.zip"
