release:
  image: php:8
  only:
    - tags
  script:
    - apt-get update
    - apt-get install zip gettext -y
    - make pack
  artifacts:
    untracked: false
    when: on_success
    paths:
      - "miguel-*.zip"
