name: Code checking by sniffer
on:
  push:
  pull_request:
jobs:
  sniff:
    name: Run sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run sniffer
        run: bash "${GITHUB_WORKSPACE}/.github/run-sniffer.sh"
