name: Code checking by sniffer
on:
  push:
  pull_request:
jobs:
  sniff:
    name: Run sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd, mysql[i], zip, exif, intl, mbstring, xml, xsl
          ini-values: xdebug.mode=coverage
          tools: composer:v2

      - name: 'Install composer dependencies'
        run: composer install --prefer-dist --no-progress --no-ansi --no-interaction

      - name: Run sniffer
        run: vendor/bin/phpcs . -v

  wc-sniff:
    name: Run WooCommerce sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd, mysql[i], zip, exif, intl, mbstring, xml, xsl
          ini-values: xdebug.mode=coverage
          tools: composer:v2

      - name: Install OS deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gettext

      - name: 'Pack and unpack for linter'
        run: |
          make pack
          unzip miguel.zip -d miguel-lint

      - name: 'Install composer dependencies'
        working-directory: miguel-lint/miguel
        run: |
          echo '
          {
            "name": "temp/temp",
            "author": "Temp, s.r.o.",
            "require-dev": {
              "squizlabs/php_codesniffer": "3.*",
              "wp-coding-standards/wpcs": "^3.0",
              "woocommerce/woocommerce-sniffs": "^0.0.2",
              "phpcompatibility/phpcompatibility-wp": "*",
              "dealerdirect/phpcodesniffer-composer-installer": "^0.7"
            },
            "config": {
              "allow-plugins": {
                "dealerdirect/phpcodesniffer-composer-installer": true
              }
            }
          }
          ' > composer.json
          composer install --prefer-dist --no-progress --no-ansi --no-interaction

          cp ../../phpcs-woocommerce.xml .

      - name: Run sniffer
        working-directory: miguel-lint/miguel
        run: vendor/bin/phpcs --standard=phpcs-woocommerce.xml --warning-severity=0 --report-source --report-full=phpcs-report.txt --ignore-annotations --extensions=php,html . -v
